version: "3.2"
services:
  nodejs:
    build: 
      context: .
    image: thanhdc/nodejs-mysql-app
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=moe-mysql-app
      - MYSQL_USER=moeuser
      - MYSQL_PASS=pass
      - MYSQL_DB=notes_db
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "30001:8005"
    container_name: moe-nodejs-app
  mysql_db_container:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD} 
      - MYSQL_DATABASE=notes_db
    container_name: moe-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql_db_container
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=moe-mysql-app
      - PMA_PORT=3306
    volumes:
      - /sessions
    container_name: moe-phpmyadmin-app
  # adminer_container:
  #   image: adminer:latest
  #   environment:
  #     ADMINER_DEFAULT_DB_DRIVER: mysql_db_container
  #     ADMINER_DESIGN: moe
  #   ports: 
  #     - "30003:80"
  #   container_name: moe-adminer-app

networks:
  frontend:
  backend:
